package com.restaurant.model;

import java.util.List;

public class MenuItem {
    private int id;  // New field for ID
    private String name;
    private String description;
    private int prepTime;
    private double price;
    private List<String> ingredients;
    private String category;
    private int quantity;  // New field for quantity

    // Constructor for new items (ID is auto-generated by the database)
    public MenuItem(String name, String description, int prepTime, double price, List<String> ingredients, String category) {
        this.name = name;
        this.description = description;
        this.prepTime = prepTime;
        this.price = price;
        this.ingredients = ingredients;
        this.category = category;
    }

    // Constructor for retrieving items from the database (ID is provided)
    public MenuItem(int id, String name, String description, int prepTime, double price, List<String> ingredients, String category) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.prepTime = prepTime;
        this.price = price;
        this.ingredients = ingredients;
        this.category = category;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getPrepTime() {
        return prepTime;
    }

    public void setPrepTime(int prepTime) {
        this.prepTime = prepTime;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public List<String> getIngredients() {
        return ingredients;
    }

    public void setIngredients(List<String> ingredients) {
        this.ingredients = ingredients;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    // Updated toString method for better formatting
    @Override
    public String toString() {
        return String.format(
                "ID: %d\nCategory: %s\nName: %s\nDescription: %s\nPreparation Time: %d minutes\nPrice: $%.2f\nIngredients: %s\n",
                id, category, name, description, prepTime, price, ingredients);
    }
}
